/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1s12015_201314408;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick
 */
public class CharacterDesign extends javax.swing.JFrame {

   public Planta aux = new Planta();
   public int cp,cz; 
   /**
     * Creates new form CharacterDesign
     */
    public CharacterDesign() {
        initComponents();
        this.setSize(800,600);
        cp = practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).cantidad;
        cz = practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).cantidad;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setText("[FOTO]");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 150, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/Grass.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 170, 180);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(550, 100, 170, 180);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECCIONAR FOTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 290, 170, 23);

        jLabel4.setBackground(new java.awt.Color(191, 222, 222));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("CREACION DE PERSONAJES");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 0, 530, 60);

        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("P. ATQ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(60, 170, 60, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NOMBRE");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(60, 80, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("P. DEF");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(60, 220, 60, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TIPO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 130, 60, 20);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(140, 220, 90, 30);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(140, 80, 130, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(140, 170, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DISPARO", "DIRECTO" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(140, 130, 90, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(120, 310, 120, 40);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PLANTAS", "ZOMBIES" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(90, 0, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/DatosBack1.jpg"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 320, 470);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 80, 320, 470);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PLANTAS", "ZOMBIES" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(440, 390, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CREADOS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(640, 360, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PERSONAJES");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(570, 340, 170, 30);

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MOSTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(530, 500, 170, 23);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CONTINUAR");
        jPanel1.add(jButton4);
        jButton4.setBounds(620, 10, 140, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ATQ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(610, 430, 30, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NOMBRE");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(600, 400, 70, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DEF");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 460, 27, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(679, 400, 90, 0);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(680, 430, 0, 0);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(680, 460, 0, 0);

        jComboBox5.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox5.setEnabled(false);
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(450, 430, 130, 30);

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LISTA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(440, 360, 110, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/Frontyard.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-110, -10, 920, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public File fichero;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int resultado;


CargarFoto ventana = new CargarFoto();

FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");

ventana.jfchCargarfoto.setFileFilter(filtro);

resultado= ventana.jfchCargarfoto.showOpenDialog(null);


if (JFileChooser.APPROVE_OPTION == resultado){


        fichero = ventana.jfchCargarfoto.getSelectedFile();
        aux.fichero = fichero;
        aux.imagen = jLabel1;
       
        try{

               ImageIcon icon = new ImageIcon(fichero.toString());

Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));

jLabel1.setText(null);
               
               jLabel1.setIcon( icono );


        }catch(Exception ex){

           
JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);
                 
        }
    
 }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      System.out.println(cp +" " + cz);
        if(jTextField1.getText().isEmpty()&& jTextField2.getText().isEmpty() && jTextField3.getText().isEmpty()){
            jTextField1.setText("Lennar Primero");
            jTextField2.setText("Lennar Primero");
            jTextField3.setText("Lennar Primero");
        }else if(jTextField1.getText().isEmpty()){
            jTextField1.setText("Lennar Primero");
        }
        else if(jTextField2.getText().isEmpty()){
            jTextField2.setText("Lennar Primero");
        }else if(jTextField3.getText().isEmpty()){
            jTextField3.setText("Lennar Primero");
        }else {
       
            if(jComboBox4.getSelectedItem().toString() == "PLANTAS"){
                if(cp>0){
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.nombre = jTextField2.getText();
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.ataque = Integer.parseInt(jTextField3.getText());
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.defensa = Integer.parseInt(jTextField1.getText());
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.tipo = jComboBox1.getSelectedItem().toString();
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.fichero = aux.fichero;
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño - cp).P.imagen = aux.imagen;
                cp--;
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField1.setText(null);
                }else{
                JOptionPane.showMessageDialog(null,"SE TERMINARON LAS PLANTAS", "ALERTA", JOptionPane.ERROR_MESSAGE);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField1.setText(null);
                }
            }else if(jComboBox4.getSelectedItem().toString() == "ZOMBIES"){
                if(cz>0){
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.nombre = jTextField2.getText();
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.ataque = Integer.parseInt(jTextField3.getText());
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.defensa = Integer.parseInt(jTextField1.getText());
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.tipo = jComboBox1.getSelectedItem().toString();
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.fichero = aux.fichero;
                practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño - cz).zoomb.imagen = aux.imagen;
                cz--;
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField1.setText(null);     
                }else{
                    JOptionPane.showMessageDialog(null,"SE TERMINARON LOS ZOMBIES", "ALERTA", JOptionPane.ERROR_MESSAGE);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField1.setText(null);
                }
            }
                for(int i =0; i<practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño;i++){
                    System.out.println(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(i).P.nombre);
                }
                
                for(int j =0; j<practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño;j++){
                    System.out.println(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(j).zoomb.nombre);
             }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
      
     
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedItem().toString() == "PLANTAS"){
        jComboBox5.setEnabled(true);
        jComboBox5.removeAllItems();
         for(int i =0;i< practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.tamaño;i++){
             jComboBox5.addItem(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).Plantas.get(i).P.nombre);        
         }    
        } 
        else if(jComboBox2.getSelectedItem().toString() == "ZOMBIES"){
        jComboBox5.setEnabled(true);
        jComboBox5.removeAllItems();
         for(int i =0;i< practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.tamaño;i++){
             jComboBox5.addItem(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).Zombies.get(i).zoomb   .nombre);        
         }    
        } 
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
