/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1s12015_201314408;

import javax.swing.JOptionPane;

public class PlayerWindow extends javax.swing.JFrame {
public String nnuevo;
    /**
     * Creates new form PlayerWindow
     */
    public PlayerWindow() {
        initComponents();
        this.setSize(400,200);
        nnuevo = null; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("JUGADOR PLANTAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 20, 150, 23);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("JUGADOR ZOMBIES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 60, 150, 23);

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("COMENZAR JUEGO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 110, 160, 50);

        jButton4.setBackground(new java.awt.Color(196, 34, 34));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BORRAR DATOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(210, 110, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/Players.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-140, -10, 620, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PPlayer datos = new PPlayer();
        datos.setVisible(true);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ZPlayer datos = new ZPlayer();
        datos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       Practica1s12015_201314408.Jugadores.get(0).J.nombre = "";
        Practica1s12015_201314408.Jugadores.get(0).J.cantidad = 0;
        try{
        for(int i=1;i<Practica1s12015_201314408.Jugadores.get(0).J.datos.tamaño;i++){
        practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.remove(i);
        }   
        }catch(Exception er){}
        
        
       Practica1s12015_201314408.Jugadores.get(1).J.nombre = "";
        Practica1s12015_201314408.Jugadores.get(1).J.cantidad = 0;
        try{
        for(int i=1;i<Practica1s12015_201314408.Jugadores.get(1).J.datos.tamaño;i++){
        practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.remove(i);
        }    
        }catch(Exception er){
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if(!practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.nombre.isEmpty()&& !practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).J.nombre.isEmpty()){
         for(int i =0;i< practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).J.datos.tamaño;i++){
              System.out.println( practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).J.datos.get(i).datosE);
            }
         System.out.println("Datos Plantas");
          for(int i =0;i< practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.tamaño;i++){
              System.out.println( practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.get(i).datosE);
            }
         
         CharacterDesign cd = new CharacterDesign();
     cd.setVisible(true);
    Graphviz g = new Graphviz();
    g.doUsuarios();
     PlayerWindow.this.dispose();
     }else{
         JOptionPane.showMessageDialog(null,"DEBE COMPLETAR LA CREACION DE JUGADORES","ALERTA",JOptionPane.ERROR_MESSAGE);
     }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
