/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1s12015_201314408;

import javax.swing.JOptionPane; 
/**
 *
 * @author Erick
 */
public class PPlayer extends javax.swing.JFrame {

    /**
     * Creates new form PPlayer
     */
    public PPlayer() {
        initComponents();
    this.setSize(400,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 60, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 180, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANTIDAD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 120, 140, 29);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(200, 120, 100, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("AGREGAR CAMPO ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 170, 200, 40);

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REGISTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 220, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/PPlayer.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-320, -230, 750, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String aux = null;
        String nombre, cantidad;
        if(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.nombre == null){
        if(jTextField1.getText().isEmpty()&& jTextField2.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
            jTextField2.setText("LLenar Primero");
        }
        else if(jTextField1.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
        }
        else if(jTextField2.getText().isEmpty()){
            jTextField2.setText("LLenar Primero");
        }
        else{
            nombre = jTextField1.getText();
            cantidad = jTextField2.getText();
              practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.nombre = nombre;
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.cantidad = Integer.parseInt(cantidad);
            
            aux = JOptionPane.showInputDialog("Escriba el dato de su campo extra:");
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.AddDato(aux);
           
        }    
        }else{
            aux = JOptionPane.showInputDialog("Escriba el dato de su campo extra:");
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.datos.AddDato(aux);
        }
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     
        String nombre, cantidad;
        if(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.nombre == null){
            if(jTextField1.getText().isEmpty()&& jTextField2.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
            jTextField2.setText("LLenar Primero");
        }
        else if(jTextField1.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
        }
        else if(jTextField2.getText().isEmpty()){
            jTextField2.setText("LLenar Primero");
        }
        else{
            nombre = jTextField1.getText();
            cantidad = jTextField2.getText();
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.nombre = nombre;
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(0).J.cantidad = Integer.parseInt(cantidad);
        
            
            
        }
        }
        PPlayer.this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPlayer().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
