/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1s12015_201314408;

import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class ZPlayer extends javax.swing.JFrame {
    /**
     * Creates new form ZPlayer
     */
    public ZPlayer() {
        initComponents();
        this.setSize(400,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(186, 46, 46));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(243, 10, 110, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CANTIDAD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 110, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 110, 160, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 60, 160, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("AGREGAR CAMPO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 160, 190, 50);

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REGISTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 220, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1s12015_201314408/ZPlayer.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-140, -140, 660, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.clear();
        ZPlayer.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String aux = null;
        String nombre, cantidad;
        if(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.isEmpty()){
        if(jTextField1.getText().isEmpty()&& jTextField2.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
            jTextField2.setText("LLenar Primero");
        }
        else if(jTextField1.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
        }
        else if(jTextField2.getText().isEmpty()){
            jTextField2.setText("LLenar Primero");
        }
        else{
            nombre = jTextField1.getText();
            cantidad = jTextField2.getText();
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(nombre);
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(cantidad);
            aux = JOptionPane.showInputDialog("Escriba el dato de su campo extra:");
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(aux);
           
        }    
        }else{
            aux = JOptionPane.showInputDialog("Escriba el dato de su campo extra:");
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(aux);
        }
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String nombre, cantidad;
        if(practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.isEmpty()){
            if(jTextField1.getText().isEmpty()&& jTextField2.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
            jTextField2.setText("LLenar Primero");
        }
        else if(jTextField1.getText().isEmpty()){
            jTextField1.setText("LLenar Primero");
        }
        else if(jTextField2.getText().isEmpty()){
            jTextField2.setText("LLenar Primero");
        }
        else{
            nombre = jTextField1.getText();
            cantidad = jTextField2.getText();
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(nombre);
            practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.add(cantidad);
            
        }
        }
        ZPlayer.this.dispose();
         for(int i =0;i< practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.size();i++){
              System.out.println( practica1s12015_201314408.Practica1s12015_201314408.Jugadores.get(1).datos.get(i));
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
